version: '3.7'

services:
  web:
    image: node:15.8-alpine3.10
    restart: always
    container_name: web
    entrypoint: [./entrypoint.sh]
    env_file: ./.env.local
    ports:
      - '8081:8080'
    working_dir: /app
    volumes:
      - ./:/app
