version: '3.7'

services:
  mb-ryder-cup:
    image: node:15.8-alpine3.10
    restart: always
    container_name: mb-ryder-cup
    command: ['npm', 'run', 'serve']
    env_file: ./.env.local
    ports:
      - '8081:8080'
    working_dir: /app
    volumes:
      - ./:/app
      - ~/dev/uploads/scorecard/player-photos:/app/public/uploads/player-photos
